from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_xai import ChatXAI
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate

